services:
  - type: web
    name: ai-content-optimizer
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: .
